### PR TITLE
Update test-unit docs

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
This page seems old. (The latest test-unit is 3.2.8)
http://test-unit.github.io/test-unit/en/file.news.html#version-3-2-8

I tried to update documents. But some tags seems incorrect.
Could you tell me how to fix it?

For example.

```diff
-    <p>Copyright (C) 2008-2017  Kouhei Sutou <a href="mailto:kou@clear-code.com">kou@clear-code.com</a></p>
+    <p>–</p>
```

I execute the following command in test-unit directory.

```
rake release:references:upload
```

### CODE REVIEW

**Comment by kou** [comment]
I don't know whether `:nodoc` works with YARD. So we need to confirm the result of our tries.

**Comment by hiroyuki-sato** [comment]
Oh, I see(`:nodoc` doesn't support Yard.)
However, The second push(force) doesn't contain the following modification.
(This means that license information doesn't change in the second push.)

I'll try it again later with `@private` tag.

```diff
-    <p>Copyright (C) 2008-2017  Kouhei Sutou <a href="mailto:kou@clear-code.com">kou@clear-code.com</a></p>
+    <p>–</p>
```

**Comment by hiroyuki-sato** [comment]
A month ago, I asked YARD developer how to persist module document file.
But, I don't get an answer yet.

https://github.com/lsegal/yard/issues/1189

**Comment by hiroyuki-sato** [comment]
I'm not sure but #19 worked as I expected. I close this PR (This PR is already old)

**Pull request closed without merging**
