### PR TITLE
Update test-unit 3.3.1 release date

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
I had forgotten update test-unit release date.

### CODE REVIEW

**Comment by kou** [comment]
I've invited you as an administrator of this repository.
You can push this repository directly when you accept it. :-)

**Comment by hiroyuki-sato** [comment]
Thank you! I joined test-unit team!
May I merge this PR?

**Comment by kou** [comment]
Sure.

**Comment by hiroyuki-sato** [comment]
Thank you!, Merged

**Pull request merged**
